server:
  port: 8081
spring:
  application:
    name: client-sample
  boot:
    manager:
      client:
        url: http://localhost:8080

# 暴露监控端点
management:
  endpoints:
    web:
      exposure:
        include: "health,env,metrics,httptrace,threaddump,jolokia,info,logfile,refresh,heapdump,loggers,auditevents,mappings,scheduledtasks,configprops,beans"
  endpoint:
    health:
      # health 默认只展示 是否在线，增加该配置后会展示更多信息
      show-details: ALWAYS