server:
  port: 8081
spring:
  application:
    name: client-sample
  boot:
    manager:
      client:
        username: admin
        password: 123
        server-application-name: server-sample
        server-context-path: admin
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
# 暴露监控端点
management:
  endpoints:
    web:
      exposure:
        include: "logdir,logcontent,health,env,metrics,httptrace,threaddump,jolokia,info,logfile,refresh,heapdump,loggers,auditevents,mappings,scheduledtasks,configprops,beans"
  endpoint:
    health:
      # health 默认只展示 是否在线，增加该配置后会展示更多信息
      show-details: ALWAYS

logging:
  file:
    path: ./logs/${spring.application.name}
    name: ${logging.file.path}/info.log