spring:
  application:
    name: server-sample
  boot:
    manager:
      server:
        authority:
          default-password: 123
          default-user-name: admin
          enabled: false
        context-path: /admin
#  cloud:
#    nacos:
server:
  port: 8080
#      server-addr: 127.0.0.1:8848