spring:
  application:
    name: server-sample
  boot:
    manager:
      server:
        authority:
          default-password: 123
          default-user-name: admin
          enabled: true
        context-path: /admin
  cloud:
    nacos:
      server-addr: 10.3.1.241:8848