spring:
  application:
    name: server-sample
  boot:
    manager:
      server:
        authority:
          default-password: 123
          default-user-name: admin
          enabled: false
        context-path: /admin