spring:
  application:
    name: server-sample
#  boot:
#    admin:
#      context-path: /admin
#      server:
#        enabled: true
manager:
  server:
    context-path: /admin
    server:
      enabled: true
#    ui:
#      cache:
#        no-cache: true
#      extension-resource-locations: file:C:/Users/pwm/Documents/project/Java Project/server-manager/manager-ui/target/dist/
#      template-location: file:C:/Users/pwm/Documents/project/Java Project/server-manager/manager-ui/target/dist/
#      cache-templates: false
#      resource-locations: file:C:/Users/pwm/Documents/project/Java Project/server-manager/manager-ui/target/dist/