spring:
  application:
    name: server-sample
#  boot:
#    admin:
#      context-path: /admin
#      server:
#        enabled: true

manager:
  server:
    context-path: /admin
    server:
      enabled: true
    instance-auth:
      default-user-name: admin
      default-password: 123
      enabled: true
#    ui:
#      cache:
#        no-cache: true
#      cache-templates: false