
package io.github.weimin96.manager.client.registration;

import org.springframework.util.Assert;

import java.util.Collections;
import java.util.HashMap;
import java.util.Map;


/**
 * 包含注册此应用程序时使用的所有信息。
 * @author pwm
 */
@lombok.Data
@lombok.ToString(exclude = "metadata")
public class Application {

	private final String name;

	private final String managementUrl;

	private final String healthUrl;

	private final String serviceUrl;

	private final Map<String, String> metadata;

	@lombok.Builder(builderClassName = "Builder")
	protected Application(String name, String managementUrl, String healthUrl, String serviceUrl,
			@lombok.Singular("metadata") Map<String, String> metadata) {
		Assert.hasText(name, "name must not be empty!");
		Assert.hasText(healthUrl, "healthUrl must not be empty!");
		this.name = name;
		this.managementUrl = managementUrl;
		this.healthUrl = healthUrl;
		this.serviceUrl = serviceUrl;
		this.metadata = new HashMap<>(metadata);
	}

	public static Builder create(String name) {
		return Application.builder().name(name);
	}

	public Map<String, String> getMetadata() {
		return Collections.unmodifiableMap(metadata);
	}

	public static class Builder {

		// Will be generated by lombok

	}

}
